name: Generate PDF and HTML

on:
  push:
    branches:
      - main # Запускать при пуше в ветку main
  pull_request: # Запускать при создании pull request
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Скачиваем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Устанавливаем Pandoc и LaTeX
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive texlive-xetex texlive-fonts-recommended texlive-latex-extra

      # Генерация HTML из README.md
      - name: Generate HTML
        run: |
          pandoc README.md -o index.html --standalone --css=styles.css

      # Генерация PDF из README.md
      - name: Generate PDF
        run: |
          pandoc README.md -o rules.pdf --pdf-engine=xelatex

      # Загружаем сгенерированные файлы как артефакты
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: generated-docs
          path: |
            index.html
            rules.pdf
